
  
 

<div class="box">
    <h4>Shop Products</h4>
    <div>
        <a href="/c-28-amps-effects.aspx">Amps &amp; Effects</a>
        <a href="/c-214-band-orchestra.aspx">Band &amp; Orchestra</a>
        <a href="/c-23-basses.aspx">Basses</a>
        <a href="/c-137-clothing-collectibles.aspx">Clothing &amp; Collectibles</a>
        <a href="/c-42-drums-percussion.aspx">Drums &amp; Percussion</a>
        <a href="/c-7-folk-instruments.aspx">Folk Instruments</a>
        <a href="/c-14-guitars.aspx">Guitars</a>
        <a href="/c-35-keyboards-digital-pianos.aspx">Keyboards &amp; Digital Pianos</a>
        <a href="/c-130-pro-audio-recording.aspx">Pro Audio &amp; Recording</a>
        <a href="/c-116-sheet-music.aspx">Sheet Music</a>
        <a href="/c-2-ukuleles.aspx">Ukuleles</a>
    </div>  
</div>
<div class="box">
    <h4>Pianos</h4>
    <div>  
        <a href="/t-departments-pianos.aspx">Piano Rentals</a>
        <a href="/t-used-piano-sales.aspx">Used Pianos</a>
        <a href="/t-departments-pianos.aspx">Departments</a>
    </div>
</div> 
<div class="box">
    <h4>Band and Orchestra Rentals</h4>
    <div>  
        <a href="/t-band-and-orchestra-instrument-rentals.aspx">Band and Orchestra Rentals</a>
    </div>
</div> 
<div class="box">
    <h4>Service &amp; Repair</h4>
    <div> 
        <a href="/t-service-and-repair-guitars-and-fretted.aspx">Guitars &amp; Fretted</a>
        <a href="/t-service-and-repair-piano.aspx">Piano</a>
        <a href="/t-service-and-repair-electronic.aspx">Electronic</a>
        <a href="/t-service-and-repair-orchestra.aspx">Orchestra</a>
        <a href="/t-service-and-repair-woodwinds-and-brass.aspx">Woodwinds &amp; Brass</a>
    </div>
</div> 
<div class="box">
    <h4>Departments</h4>
    <div> 
        
        <a href="/t-departments-amps-and-effects.aspx">Amps &amp; Effects</a> 
        <a href="/t-departments-band-and-orchestra.aspx">Band &amp; Orchestra</a>
        <a href="/t-departments-guitars-and-fretted-instruments.aspx">Guitars &amp; Fretted Instruments</a>
        <a href="/t-departments-keyboards.aspx">Keyboards</a>
        <a href="/t-departments-percussion-and-drums.aspx">Percussion &amp; Drums</a>
        <a href="/t-departments-pro-audio-and-recording.aspx">Pro Audio &amp; Recording</a>
        <a href="/t-departments-sheet-music.aspx">Sheet Music</a>
    </div>
</div> 
<div class="box">
    <h4>About us</h4>
    <div> 
        
        <a href="t-about.aspx">About us</a> 
    </div>
</div> 
<div class="box">
    <h4>Account</h4>
    <div> 
        
        <a href="/signin.aspx">Login</a>
        <a href="/account.aspx">My Account</a> 
    </div>
</div> 
   
<div class="box">
    <h4>Connect</h4>
    <div>
        <span>Sign up for our newsletter</span>
        <div class="sign-up">

            <!--signup form-->
            <form name="ccoptin" action="http://visitor.r20.constantcontact.com/d.jsp" target="_blank" method="post"> 
                <!--<input type="hidden" name="llr" value=""/>
                                <input type="hidden" name="m" value=""/>
                                <input type="hidden" name="p" value="oi"/>
                                <input id="emailSignUpBox" type="text" name="ea" value="">
                                <input id="emailSignUpBtn" type="submit" name="go" value="Go" class="submit" />-->
            </form>
            <script type="text/javascript" src="http://www.formstack.com/forms/js.php?1577532-SFYHXvTksW-v3&amp;jsonp"></script>
             
            <noscript>
            &lt;a href="http://www.formstack.com/forms/?1577532-SFYHXvTksW" title="Online Form"&gt;Online Form - Constant Contact Signup Form&lt;/a&gt;
            </noscript>
            <div style="text-align:right; font-size:x-small;display:none;">
                <a href="http://www.formstack.com?utm_source=h&amp;utm_medium=jsembed&amp;utm_campaign=fa&amp;fa=h,1577532" title="Web Form Builder">Web Form Builder</a>
            </div>

            <!--signup form-->

        </div>
    </div>
 
    <div class="socials"> 
        <a class="youtube" href="https://www.youtube.com/user/StraitMusicAustin"></a>
        <a class="instagram" href="https://instagram.com/straitmusicaustin/"></a>
        <a class="twitter" href="https://twitter.com/straitmusicco"></a>
        <a class="google" href="https://plus.google.com/+StraitMusicCompany/"></a>
        <a class="facebook" href="https://www.facebook.com/Straitmusic"></a>
        <a class="clear" href=""></a>
    </div> 
</div> 